// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeTsmpml5F76ID_dTYPD_B6cAuU1h6qnM',
    appId: '1:602513846772:web:08eafeedaa09cfa4c149a1',
    messagingSenderId: '602513846772',
    projectId: 'sabha-hq',
    authDomain: 'sabha-hq.firebaseapp.com',
    storageBucket: 'sabha-hq.firebasestorage.app',
    measurementId: 'G-23320M9BYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYa_KmPkiGd5VLxQGU4aRAvcIH0bgZtHY',
    appId: '1:602513846772:android:cefd76a816452ba4c149a1',
    messagingSenderId: '602513846772',
    projectId: 'sabha-hq',
    storageBucket: 'sabha-hq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuOM6sI3MYR1aB7QAELRWxIHyooCGhd1Q',
    appId: '1:602513846772:ios:5188fda4191728abc149a1',
    messagingSenderId: '602513846772',
    projectId: 'sabha-hq',
    storageBucket: 'sabha-hq.firebasestorage.app',
    iosBundleId: 'com.example.sabhaHq',
  );
}
