import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'app.dart';

void main() async {
  // Ensure Flutter engine is initialized before calling native bindings
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase for Web/Mobile
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(
    // ProviderScope stores the state of all Riverpod providers
    const ProviderScope(child: SabhaApp()),
  );
}
